import type { Metadata } from "next";
import "./globals.css";
import { IBM_Plex_Sans, IBM_Plex_Mono } from "next/font/google";
import SocketComp from "@/components/SocketComp";
import WalletAdapter from "@/components/walletAdapter";
import NavBar from "@/components/Navigation";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




const sans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-sans", 
});


const mono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-mono",
});



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${sans.variable} ${mono.variable} h-full dark antialiased `}
    >
      <body className="min-h-full flex flex-col font-sans">
        <SocketComp/>
        <WalletAdapter>
          <NavBar/>
          {children}
        </WalletAdapter>
        
        </body>
    </html>
  );
}
